name: lpass-sso

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: auto/lint
      - run: auto/build
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'dist/*.tar.gz'
          tag: v${{ github.ref }}
          overwrite: false
          file_glob: true

